name: Terraform

on:
  push:
    branches:
      - main
      - "feature/*"

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=plan.tfplan

      - name: Terraform Plan Output
        run: terraform show -json plan.tfplan > plan.json

      - name: Upload plan
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: plan.json

